# Generated by Django 2.0 on 2019-03-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.IntegerField(default=0, verbose_name="Не нравится"),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Нравится"),
        ),
    ]
