# Generated by Django 2.0 on 2019-03-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
